### ISSUE TITLE
Coderef last in forlines, but first elsewhere?

### ISSUE THREAD

**Issue by cxw42** [jmaslak/File-ByLine#3]
Just ran across this in metacpan/recent --- looks very useful!  Less an issue than a question --- why does `forlines` take its coderef as the second argument, when `greplines` and `maplines` take theirs as the first?  I can readily imagine myself tripping over that in the future :) .  Thanks!

**Comment by jmaslak** [comment]
I debated the order on forlines a lot - but having the code at the end just seems more natural to me.

The idea was that for grep/map, I would typically would have small pieces of code there, while for forlines it could be a lot longer - spanning multiple lines frequently, so I wanted to minimize how far back you had to look to find out what the other parameter(s) belong with.  I could change greplines/maplines, but then I would have the problem of them being ordered differently than the built-in map/grep.  So I have the less-than-satisfying solution of putting the code in a different place for the forlines than for the grep/map.

I am going to leave this open though because I should probably explain my reasoning in the documentation.

**Comment by cxw42** [comment]
Makes sense, and thanks for the quick response!  What about a complement to forlines that is `dolines BLOCK FILENAME`?  Then the user would have a choice.  E.g., `dolines { s/^/#/; say } 'foo.pl'` seems fairly natural to me.

**Comment by jmaslak** [comment]
Oooh, I like that idea!  I'll put that in the next version.

**Comment by jmaslak** [comment]
I've created a 1.003 trial version I'll push out in a few minutes.  It won't get indexed, so your CPAN client probably won't see it (unless you tell it to fetch trial versions), but that will let me confirm this works across all platforms.  Assuming that turns out well, I'll be pushing this as 1.004 in a day or two.  I'll leave this open until pushed.

See PR #4

**Comment by jmaslak** [comment]
Version 1.005 was just pushed, with the new dolines routine.  I'm going to go ahead and close this issue - thanks for the suggestion!

**Comment by cxw42** [comment]
Thank you for the quick turnaround!  (And for making Parallel optional - I noticed when installing that it has quite a large dependency tree of its own!)
